components:
  schemas:
  responses:
    outOfStock:
      type: object
      properties:
        message:
          type: string
          description: Response message description
      example:
        message: Product out of stock
    securitySchemes:
    newTicket:
      type: object
      properties:
        message:
          type: string
          description: Response message description
        ticket:
          type: object
          properties:
            code:
              type: string
              description: ticket unique code
            purchase_datetime:
              type: string
              description: purchase date and time
            products:
              type: array
              description: array of products in the ticket
              items:
                type: object
                properties:
                  _id:
                    type: string
                    description: product id
                  quantity:
                    type: string
                    description: product quantity
            amount:
              type: number
              description: ticket total amount
            purchaser:
              type: string
              description: email address of the purchaser
            _id:
              type: string
              description: ticket id
      example:
        message: Ticket generated successfully
        ticket:
          code: 323013D51W27
          purchase_datetime: Wed, 13 Dec 2023 13:57:20 GMT
          products:
            - _id: 64c3cc0d06404a4aff717828
              quantity: 1
          amount: 39999
          purchaser: user@gmail.com
          _id: 6579b8405ef9b9a2293813b2
    cartEmptyPost:
      type: object
      properties:
        status:
          type: number
          description: Response status code
        message:
          type: string
          description: Response message description
        from:
          type: string
          description: Response from      
      example:
        status: 404
        message: Cart is empty
        from: POST /api/tickets controller
    
    cartEmptyGet:
      type: object
      properties:
        status:
          type: number
          description: Response status code
        message:
          type: string
          description: Response message description
        from:
          type: string
          description: Response from      
      example:
        status: 404
        message: Cart is empty
        from: GET /api/tickets controller
    
    errorTicket:
      type: object
      properties:
        status:
          type: number
          description: Response status code
        message:
          type: string
          description: Response message description
        from:
          type: string
          description: Response from
      example:
        status: 500
        message: Something went wrong
        from: POST /api/tickets controller
    
    errorTicketGET:
      type: object
      properties:
        status:
          type: number
          description: Response status code
        message:
          type: string
          description: Response message description
        from:
          type: string
          description: Response from
      example:
        status: 500
        message: Something went wrong
        from: GET /api/tickets controller
    
    noAuth:
      type: object
      properties:
        error:
          type: boolean
          description: error status
        message:
          type: string
          description: Response message description
      example:
        error: true
        message: No authorization

    notLoggedIn:
      type: object
      properties:
        error:
          type: boolean
          description: error status
        message:
          type: string
          description: Response message description
      example:
        error: true
        message: Error no auth token
    ticketAmount:
      type: object
      properties:
        message:
          type: string
          description: Response message description
        totalAmount:
          type: number
          description: total amount of the ticket
        products:
          type: array
          description: array of products in the ticket
          items:
            type: object
            properties:
              productID:
                type: string
                description: product id
              quantity:
                type: string
                description: product quantity       
      example:
        meessage: Total amount calculated successfully
        totalAmount: 15999
        products:
          - productID: 5f9d88b9c4b3f3b3c8d9e6b1
            quantity: 1
          - productID: 5f9d88b9c4b3f3b3c8d9e6b2
            quantity: 1
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken

paths:
  /api/tickets:
    post:
      summary: Create a ticket based on a user's cart
      tags:
        - Tickets
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Product out of stock
          content:
            application/json:
              schema:
                $ref: '#/components/responses/outOfStock'
        '201':
          description: Ticket created
          content:
            application/json:
              schema:
                $ref: '#/components/responses/newTicket'
        '401':
          description: No user logged in
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notLoggedIn'
        '403':
          description: No authorization
          content:
            application/json:
              schema:
                $ref: '#/components/responses/noAuth'
        '404':
          description: Cart is empty
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cartEmptyPost'
        '500':
          description: Error creating ticket
          content:
            application/json:
              schema:
                $ref: '#/components/responses/errorTicket'
    get:
      summary: Get ticket amout
      tags:
        - Tickets
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Ticket amount
          content:
            application/json:
              schema:
                $ref: '#/components/responses/ticketAmount'
        '401':
          description: No user logged in
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notLoggedIn'
        '403':
          description: No authorization
          content:
            application/json:
              schema:
                $ref: '#/components/responses/noAuth'
        '404':
          description: Cart is empty
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cartEmptyGet'
        '500':
          description: Error calculating ticket amount
          content:
            application/json:
              schema:
                $ref: '#/components/responses/errorTicketGET'